### ISSUE TITLE
debian 10 x64, "alcali-package-install-virtualenv-managed" failes

### ISSUE THREAD

**Issue by bitchriss** [latenighttales/alcali-formula#5]
Hey there,

i played a while with salt and now i wanted to test that nice looking GUI.
So i created a new VM (to not play in my prod env), installed debian 10, created a salt-master (3000.2) with api, auth, mysql (+python3-mysqldb), rest-auth and ofc the mariadb-server.

I configured the pillar to get the alcali v3000.1.0

When i run the state to install alcali i get the following output (shortend):

>----------
          ID: alcali-package-install-virtualenv-managed
    Function: virtualenv.managed
        Name: /opt/alcali/.venv
      Result: False
     Comment: Created new virtualenv
              Collecting ansi2html==1.5.2
                Downloading ansi2html-1.5.2.tar.gz (27 kB)
              DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
              ERROR: Could not find a version that satisfies the requirement Django==3.0.5 (from -r /tmp/tmp55pjep7t/prod.txt (line 2)) (from versions: 1.1.3, 1.1.4, 1.2, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.7, 1.4, 1.4.1, 1.4.2, 1.4.3, 1.4.4, 1.4.5, 1.4.6, 1.4.7, 1.4.8, 1.4.9, 1.4.10, 1.4.11, 1.4.12, 1.4.13, 1.4.14, 1.4.15, 1.4.16, 1.4.17, 1.4.18, 1.4.19, 1.4.20, 1.4.21, 1.4.22, 1.5, 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.5.5, 1.5.6, 1.5.7, 1.5.8, 1.5.9, 1.5.10, 1.5.11, 1.5.12, 1.6, 1.6.1, 1.6.2, 1.6.3, 1.6.4, 1.6.5, 1.6.6, 1.6.7, 1.6.8, 1.6.9, 1.6.10, 1.6.11, 1.7, 1.7.1, 1.7.2, 1.7.3, 1.7.4, 1.7.5, 1.7.6, 1.7.7, 1.7.8, 1.7.9, 1.7.10, 1.7.11, 1.8a1, 1.8b1, 1.8b2, 1.8rc1, 1.8, 1.8.1, 1.8.2, 1.8.3, 1.8.4, 1.8.5, 1.8.6, 1.8.7, 1.8.8, 1.8.9, 1.8.10, 1.8.11, 1.8.12, 1.8.13, 1.8.14, 1.8.15, 1.8.16, 1.8.17, 1.8.18, 1.8.19, 1.9a1, 1.9b1, 1.9rc1, 1.9rc2, 1.9, 1.9.1, 1.9.2, 1.9.3, 1.9.4, 1.9.5, 1.9.6, 1.9.7, 1.9.8, 1.9.9, 1.9.10, 1.9.11, 1.9.12, 1.9.13, 1.10a1, 1.10b1, 1.10rc1, 1.10, 1.10.1, 1.10.2, 1.10.3, 1.10.4, 1.10.5, 1.10.6, 1.10.7, 1.10.8, 1.11a1, 1.11b1, 1.11rc1, 1.11, 1.11.1, 1.11.2, 1.11.3, 1.11.4, 1.11.5, 1.11.6, 1.11.7, 1.11.8, 1.11.9, 1.11.10, 1.11.11, 1.11.12, 1.11.13, 1.11.14, 1.11.15, 1.11.16, 1.11.17, 1.11.18, 1.11.20, 1.11.21, 1.11.22, 1.11.23, 1.11.24, 1.11.25, 1.11.26, 1.11.27, 1.11.28, 1.11.29)
              ERROR: No matching distribution found for Django==3.0.5 (from -r /tmp/tmp55pjep7t/prod.txt (line 2))
     Started: 00:27:50.068798
    Duration: 5348.629 ms
     Changes:
              ----------
              new:
                  Python 2.7.16
----------

Research shows that (like that error-message tells me) django 3.0.5 needs python3, change-log shows that python 2.7.16 got installed...

My pillar "alcali.sls" looks like this:
----------
>alcali:
  deploy:
    repository: https://github.com/latenighttales/alcali.git
    branch: v3000.1.0
    user: alcali
    group: alcali
    directory: /opt/alcali
    service: alcali
    runtime: python3
  gunicorn:
    name: 'config.wsgi:application'
    host: '0.0.0.0'
    port: 5000
    workers: {{ grains['num_cpus'] }}
  config:
    db_backend: mysql
    db_name: salt
    db_user: salt
    db_password: alphanumeric-password
    db_host: localhost
    db_port: 3306
    master_minion_id: srv-salt-01.monitoring.mynetwork.de
    secret_key: alphanumeric-password
    allowed_hosts: '*'
    salt_url: 'https://srv-salt-01.monitoring.mynetwork.de:8080'
    salt_auth: rest
----------

Do you have any hint for me to fix that problem?

Greetings
Chriss

**Comment by vquie** [comment]
@bitchriss 
Does my PR fix your issue?

**Comment by mattLLVW** [comment]
Should be closed by #6
