### ISSUE TITLE
Saltstack-formulas Organization Contribution

### ISSUE THREAD

**Issue by sticky-note** [latenighttales/alcali-formula#9]
Hi @mattLLVW, would you mind this formula be cloned in https://github.com/saltstack-formulas/ organization so it can benefit the last evolution of saltstack-formulas, CI/CD, versioning and all community can contribute to it.
Please respond to this message and we can do all the necessary to clone this repo in the https://github.com/saltstack-formulas/ organization

**Comment by mattLLVW** [comment]
It would be great, please do.

One thing to note: currently this formula use git to install Alcali, i'm not sure that's the best way to do it (see [here](https://github.com/latenighttales/alcali-formula/blob/master/alcali/package/install.sls#L52)). Using pip would probably be better.

I'll put a disclaimer with a link to the repository in the readme of this repo.
Thanks.

**Comment by sticky-note** [comment]
Ok, the repo has been forked,
https://github.com/saltstack-formulas/alcali-formula.git
You've been invited to be maintainer of the fork, check your mails
I invite you to update your documentation accordingly.

Thanks for your awesome project.

**Comment by sticky-note** [comment]
Thanks @mattLLVW . Closing
